services:
  maislusitania-app:
    build: frontend
    container_name: maislusitania-app
    ports:
      - "8080:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - maislusitania-db
    networks:
      - maislusitania-network

  maislusitania-admin:
    build: backend
    container_name: maislusitania-admin
    ports:
      - "8081:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - maislusitania-db
    networks:
      - maislusitania-network

  maislusitania-api:
    build: backend
    container_name: maislusitania-api
    ports:
      - "8082:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - maislusitania-db
    networks:
      - maislusitania-network

  maislusitania-db:
    image: mysql:5.7
    container_name: maislusitania-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    volumes:
      - maislusitania-db-data:/var/lib/mysql
      - ../yii2advanced.sql:/docker-entrypoint-initdb.d/yii2advanced.sql
    networks:
      - maislusitania-network

  maislusitania-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: maislusitania-phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=maislusitania-db
      - PMA_USER=root
      - PMA_PASSWORD=verysecret
    depends_on:
      - maislusitania-db
    networks:
      - maislusitania-network

volumes:
  maislusitania-db-data:
    driver: local

networks:
  maislusitania-network:
    driver: bridge
